project_name: kured
before:
  hooks:
    - go mod tidy
builds:
  - id: "kured"
    main: ./cmd/kured
    binary: kured
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: "node-reboot-detector"
    main: ./cmd/node-reboot-detector
    binary: node-reboot-detector
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: "node-reboot-reporter"
    main: ./cmd/node-reboot-reporter
    binary: node-reboot-reporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: "node-maintenance-scheduler"
    main: ./cmd/node-maintenance-scheduler
    binary: node-maintenance-scheduler
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

snapshot:
  name_template: "{{ .ShortCommit }}"

release:
  disable: true

changelog:
  disable: true
