project_name: kured
before:
  hooks:
    - go mod tidy
builds:
  - id: "kured"
    main: ./cmd/kured
    binary: kured
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - linux_arm_v7
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: "reboot-required-detector"
    main: ./cmd/reboot-required-detector
    binary: reboot-required-detector
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - linux_arm_v7
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: "maintenance-scheduler"
    main: ./cmd/maintenance-scheduler
    binary: maintenance-scheduler
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - linux_arm_v7
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

snapshot:
  name_template: "{{ .ShortCommit }}"

release:
  disable: true

changelog:
  disable: true