builds:
  - id: node-maintenance-scheduler
    dir: .
    main: ./cmd/node-maintenance-scheduler
  - id: node-reboot-detector
    dir: .
    main: ./cmd/node-reboot-detector
  - id: node-reboot-reporter
    dir: .
    main: ./cmd/node-reboot-reporter
defaultPlatforms:
  - linux/amd64
  - linux/arm64
  - linux/arm
defaultLdflags:
  - -s -w -X main.version={{if and (ne .Env.RELEASE "") (or (eq .Env.RELEASE "true") (eq .Env.RELEASE "TRUE") (eq .Env.RELEASE "True"))}}{{Git.Tag}}{{else}}{{Git.ShortCommit}}{{end}}
# needs to check if trimpath is used