---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maintenance-scheduler
  # this needs to map where maintenance-scheduler is installed
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "kured:maintenance-reader"
  # This needs to map the cm's namespace to read the maintenances from
  namespace: kube-system
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ] # for maintenances
    verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "kured:maintenance-scheduler"
  # This needs to map the cm's namespace to read the maintenances from
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "kured:maintenance-reader"
subjects:
  - kind: ServiceAccount
    name: maintenance-scheduler
    # this needs to map where maintenance-scheduler is installed
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kured:maintenance-scheduler"
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "nodes/status" ]
    verbs: [ "update", "patch" ] # need to remove update asap.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kured:maintenance-scheduler"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kured:maintenance-scheduler"
subjects:
  - kind: ServiceAccount
    name: maintenance-scheduler
    # this needs to map where maintenance-scheduler is installed
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-scheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: maintenance-scheduler
    app.kubernetes.io/component: reporter
    app.kubernetes.io/part-of: kured
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: maintenance-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: maintenance-scheduler
        app.kubernetes.io/component: reporter
        app.kubernetes.io/part-of: kured
    spec:
      serviceAccountName: maintenance-scheduler
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      restartPolicy: Always
      containers:
        - name: maintenance-scheduler
          image: ghcr.io/kubereboot/maintenance-scheduler:dev
          imagePullPolicy: IfNotPresent
          args:
            - "--debug"
          ports:
            - containerPort: 8080
              name: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: maintenance-scheduler
  namespace: kube-system
  labels:
    app.kubernetes.io/name: maintenance-scheduler
    app.kubernetes.io/component: reporter
    app.kubernetes.io/part-of: kured
spec:
  clusterIP: ""
  selector:
    app: maintenance-scheduler
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics