---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-reboot-detector-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-reboot-detector-role
  namespace: kube-system
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-reboot-detector-rb
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-reboot-detector-role
subjects:
  - kind: ServiceAccount
    name: node-reboot-detector-sa
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-reboot-detector
  namespace: kube-system
  labels:
    system: kured
spec:
  selector:
    matchLabels:
      app: node-reboot-detector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-reboot-detector
        system: kured
    spec:
      serviceAccountName: node-reboot-detector-sa
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      restartPolicy: Always
      volumes:
        - name: sentinel
          hostPath:
            path: /var/run
            type: Directory
      containers:
        - name: node-reboot-detector
          image: ghcr.io/kubereboot/node-reboot-detector:dev
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              name: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
          env:
            # Pass in the name of the node on which this pod is scheduled
            # for use with drain/uncordon operations and lock acquisition
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /sentinel
              name: sentinel
              readOnly: true
          command:
            - /usr/bin/node-reboot-detector
            - --period=5s # Development value. Please increase it in production.
---
apiVersion: v1
kind: Service
metadata:
  name: node-reboot-detector
  namespace: kube-system
spec:
  clusterIP: None
  selector:
    app: node-reboot-detector
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
