---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reboot-required-detector
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kured:reboot-required-detector"
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get" ]
  - apiGroups: [ "" ]
    resources: [ "nodes/status" ]
    verbs: [ "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kured:reboot-required-detector"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kured:reboot-required-detector"
subjects:
  - kind: ServiceAccount
    name: reboot-required-detector
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reboot-required-detector
  namespace: kube-system
  labels:
    app.kubernetes.io/name: reboot-required-detector
    app.kubernetes.io/component: reporter
    app.kubernetes.io/part-of: kured
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reboot-required-detector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reboot-required-detector
        app.kubernetes.io/component: reporter
        app.kubernetes.io/part-of: kured
    spec:
      serviceAccountName: reboot-required-detector
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      restartPolicy: Always
      volumes:
        - name: sentinel
          hostPath:
            path: /var/run
            type: Directory
      containers:
        - name: reboot-required-detector
          image: ghcr.io/kubereboot/reboot-required-detector:dev
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              name: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 3
          env:
            # Pass in the name of the node on which this pod is scheduled
            # for use with drain/uncordon operations and lock acquisition
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /sentinel
              name: sentinel
              readOnly: true
          args:
            - --period=5s # Development value. Please increase it in production.
            - --debug # Development value. Please remove it in production.
---
apiVersion: v1
kind: Service
metadata:
  name: reboot-required-detector
  namespace: kube-system
  labels:
    app.kubernetes.io/name: reboot-required-detector
    app.kubernetes.io/component: reporter
    app.kubernetes.io/part-of: kured
spec:
  clusterIP: ""
  selector:
    app.kubernetes.io/name: reboot-required-detector
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
