#This tests if our kustomize manifests still work with an update
#of kustomize or with an update of our manifests
name: Kustomize deploy

on:
  pull_request:
    paths:
      - "**/kured-*.yaml"
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy-with-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      # We need to unpin kind-action so we can test is new versions of kind
      # and therefore kubernetes will break with our manifests
      # This creates a 1 node cluster.
      - name: Create a default kind cluster
        uses: helm/kind-action@master

      # kind-action already installed kind and kubectl.
      - name: Deploy using kustomize/kubectl
        run: |
          kubectl apply -k .github/kustomize

      - name: Ensure kured can come up
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 30
          retry_wait_seconds: 10
          # DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE should all be =1
          command: kubectl get ds -n kube-system | egrep "kured.*1.*1.*1.*1.*1" > /dev/null
